#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# if you're looking for where to put the actual pi,
# it's in scripts/superpigen.py, line 9

import scripts.superpigen

if __name__ == '__main__':
    scripts.superpigen.main()
